openapi: 3.1.0
info:
  title: Mapache MCP Bridge
  version: "1.0.1"
servers:
  - url: /
paths:
  /healthz:
    get:
      operationId: healthz
      responses:
        "200":
          description: ok
          content:
            text/plain:
              schema: { type: string }
  /tools:
    get:
      operationId: tools
      description: List connected MCP servers/tools.
      responses:
        "200":
          description: Tool list
          content:
            application/json:
              schema:
                type: object
                properties:
                  hosted: { type: array, items: { type: object } }
                  streamable: { type: array, items: { type: object } }
                  count: { type: integer }
  /run:
    post:
      operationId: run
      description: Run an MCP-enabled agent against the user's prompt.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: The user's instruction for the agent.
      responses:
        "200":
          description: Agent response
          content:
            application/json:
              schema:
                type: object
                properties:
                  output: { type: string }
                  toolEvents: { type: array, items: { type: object } }
                  citations: { type: array, items: { type: object } }
        "500":
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
